### PR TITLE
Qnh override

### PR DESCRIPTION
**Pull request by talbotmcinnis**
This started with the goal of being able to work around the temperature/pressure issue we discovered a while back.  Our squad is very sensitive to the expected QNH setting causing an exact match to aircraft values at the EOR areas, 

QNH 30.02 is a supported option.

However this exposed challenges applying that override to QFE.  Thus I included something I've been meaning to do anyway, add "NO QFE" and "NO HPA" options to suppress those from the remarks sections.

As always, welcoming all feedback.  Cheers.

### CODE REVIEW

**Comment by rkusa** [comment]
Thanks for the PR! Would you mind giving https://github.com/rkusa/DATIS/pull/93 to see if we maybe don't even need the override?

**Comment by talbotmcinnis** [comment]
Will do!  Exciting!

**Comment by rkusa** [comment]
`v3.0.1` hopefully fixes the QNH deviations so that we don't need the QNH override. Adding `NO QFE` and `NO hPa` (we might wanna make `hPa` case-insensitive so that it works for both `NO HPA` and `NO hPA`, wdyt?) is still fine for me.

**Comment by talbotmcinnis** [comment]
Good idea regarding case sensitivity.  I will remove the qnh override now.  I also am not attached to the exact phrasing so feel free to make a change if you wish.  I'll try to push my changes tonight or Monday.

**Comment by talbotmcinnis** [comment]
Ok, QNH OVERRIDE option has been removed, NO X options are now case insensitive, and the branch has been deconflicted.

Let me know if you see anything else, otherwise as far as I'm concerned this is ready to merge :)

**Review by rkusa — APPROVED** [review]
Looks good, thanks 👍👏

**Comment by rkusa** [comment]
⛵ released as part of https://github.com/rkusa/DATIS/releases/tag/3.1.0

**Pull request merged**
